version: '3'

volumes:
  maven-data:
  db-data:

services:

  postgres:
    image: postgres:alpine3.18
    container_name: "DB"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=engProject
  engPro:
    image: 'docker-spring-boot-postgres:latest'
    depends_on:
      - postgres
    build:
      context: .
    container_name: "APP"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
